# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/btracer',
                'doc_host': 'https://salk-ee.github.io',
                'git_url': 'https://github.com/salk-ee/btracer',
                'lib_path': 'btracer'},
  'syms': {'btracer.core': {'btracer.core.foo': ('core.html#foo', 'btracer/core.py')}}}
